### ISSUE TITLE
1.0.5 tests fail on centos 6.x

### ISSUE THREAD

**Issue by totaam** [aresch/rencode#10]
This looks like a python2.6 compatibility issue, here is the error message:

```
python2 test_rencode.py
...........E.............................
======================================================================
ERROR: test_decode_int_big_number (__main__.TestRencode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_rencode.py", line 146, in test_decode_int_big_number
    toobig = '={}\x7f'.format('9'*65).encode()
ValueError: zero length field name in format
```

**Comment by aresch** [comment]
Works fine for me in python 3.5 and python 2.7.  Honestly, nobody should be using python 2.6 anymore.  I don't have 2.6 installed so I can't really test a fix, if you want to submit a pull request I can review it.

**Comment by totaam** [comment]
I really wished I could move everyone away from centos 6, but sadly that's not going to happen anytime soon. So in the meantime, please use this form (tested on py 2.6, 2.7 and 3.5):
`'={x}\x7f'.format(x='9'*65).encode()`

**Comment by aresch** [comment]
fe367e1c9b5bfb8cc0ef73624989c2bbaf4ab6a6

I've committed that change.

Do you need me to make a new release? This is just a test case.

**Comment by totaam** [comment]
Thanks!
No need for a new release from my end: I've changed the spec file to skip the tests on that platform for now.
