### ISSUE TITLE
pip install failing 

### ISSUE THREAD

**Issue by ngodber** [aresch/rencode#26]
Hi,

Seeing the following error:

![image](https://user-images.githubusercontent.com/11834846/59957718-63d40280-94de-11e9-927d-7bbb62f42dc4.png)

Just wanted to log in case this was not a known issue.

**Comment by ngodber** [comment]
I see this is related to #22

**Comment by alphabet5** [comment]
It's related. pypi is not updated yet. 

Download the git repo, cd to rencode-master and run 'pip3 install .' and it should install without pip.

**Comment by ngodber** [comment]
Ok  thanks.
