### ISSUE TITLE
1.0.3 still in source

### ISSUE THREAD

**Issue by totaam** [aresch/rencode#6]
`
$ tar -zxvf rencode-1.0.4.tar.gz;
$ PYTHONPATH=./rencode-1.0.4/ python -c "import rencode;print(rencode.__file__, rencode.__version__)";
('rencode-1.0.4/rencode/__init__.pyc', ('Python', 1, 0, 3))
`

Same if you look at the source.

**Comment by aresch** [comment]
I re-did the tag and release earlier today because I had forgotten to update the setup.py.  Can you try a fresh download?

**Comment by totaam** [comment]
`
$ md5sum rencode-1.0.4.tar.gz
ecc0fea0a20b49c6f252d4fea0238641  rencode-1.0.4.tar.gz

$ grep __version__ rencode-1.0.4/rencode/rencode_orig.py
__version__ = ("Python", 1, 0, 3)
`
Nope, still there.

**Comment by aresch** [comment]
Oh, we set the version in file itself.. I'll update that and roll another tarball.

**Comment by totaam** [comment]
Fixed. Thanks!

**Comment by totaam** [comment]
Please also update pypi:
https://pypi.python.org/pypi/rencode/1.0.4

**Comment by aresch** [comment]
Yea, I've been trying to but pypi seems to be having some issues at the moment.  I'll keep trying, but it might not be till tomorrow. Sorry.

**Comment by aresch** [comment]
Looks like it's working now.

**Comment by totaam** [comment]
It is, thanks.
