### ISSUE TITLE
missing version bump in rencode_orig

### ISSUE THREAD

**Issue by totaam** [aresch/rencode#9]
I think this had happened before..
It is still showing as 1.0.4, despite this changeset updating to 1.0.5:
https://github.com/aresch/rencode/commit/a5ab0fb6c3603d1e9c53e2cfc262b2288d2912d8

I only detected it because I tried to run from the source directory, which fails to load the cythonized version.

If all is well after that, please also push an update to pypi.

**Comment by cas--** [comment]
I see the version issue was fixed: 718a07cc646a2

Andar can you release on github and push to pypi, thanks.

**Comment by aresch** [comment]
Done.
